### ISSUE TITLE
Problem with robbery..

### ISSUE THREAD

**Issue by Roazen** [Testaross/ostorerobbery#1]
Hey.. i have all what i need for script.. but it doesnt show on ox_target the roberry..

The bag i have on ox_inv but the prop doesnt show on my char..

Any tips for fix?

**Comment by cellooohh** [comment]
> Hey.. i have all what i need for script.. but it doesnt show on ox_target the roberry..
> 
> The bag i have on ox_inv but the prop doesnt show on my char..
> 
> Any tips for fix?

In the client, there is still a = in the 1st line. I removed this, then it worked for me.

**Comment by Roazen** [comment]
> 

and where ?

**Comment by Testaross** [comment]
script has been rewritten
